repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0  # check laatste release
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4  # check laatste release
    hooks:
      - id: ruff
        args: [--fix]
