repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        # lokaal: format automatisch
        # in CI: alleen checken
        args: []
        ci:
          args: [--check, --diff]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        # lokaal: fix automatisch
        args: [--fix]
        ci:
          args: [--exit-non-zero-on-fix]
      - id: ruff-format
        # lokaal: format automatisch
        args: []
        ci:
          args: [--check]
