version: '3.8'

networks:
  discord-network:
    driver: bridge

services:
  mongo:
    image: mongo
    container_name: mongo
    networks:
      - discord-network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: yourpassword123!
      TLSENABLED: false
    volumes:
      - mongo-data:/data/db
    restart: always

  webapp:
    image: tibot-v3
    depends_on:
      - mongo
    networks:
      - discord-network
    env_file:
      - .env
    environment:
      TLSENABLED: false      
    restart: always

volumes:
  mongo-data:
